// Next built in imports
import type { Metadata } from "next";
// Css imports
import Footer from "@/components/common/footer/footer";
import Header from "@/components/common/header/header";
import { ReduxProvider } from "@/utils/providers/redux-provider";
import "./globals.css";

// metadata
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-white flex justify-center font-yekan">
        <ReduxProvider>
          <main className="w-[85.5%] ">
            <Header />
            {children}
            <Footer />
          </main>
        </ReduxProvider>
      </body>
    </html>
  );
}
