// Next built in imports
import type { Metadata } from "next";
// Css imports
import Footer from "@/components/common/footer/footer";
import Header from "@/components/common/header/header";
import { ReduxProvider } from "@/utils/providers/redux-provider";
import "./globals.css";
import FloatingActions from "@/components/common/FAB/fab";

// metadata
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="">
      <body className="bg-background dark:bg-background-dark text-text dark:text-text-dark flex justify-center font-yekan">
        <ReduxProvider>
          <main className="w-[85.5%] ">
            <Header />
            {children}
            <Footer />
          </main>
          <FloatingActions />
        </ReduxProvider>
      </body>
    </html>
  );
}
