// Next built in imports
import type { Metadata } from "next";
// next-intl
import { NextIntlClientProvider, hasLocale } from "next-intl";
import { routing } from "@/i18n/routing";
// Third party components
import Footer from "@/components/common/footer/footer";
import Header from "@/components/common/header/header";
import FloatingActions from "@/components/common/FAB/fab";
// Redux provider
import { ReduxProvider } from "@/utils/providers/redux-provider";
// Css imports
import "./globals.css";

// metadata
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}>) {
  const { locale } = await params;
  if (!hasLocale(routing.locales, locale)) {
    return "not found";
  }

  const direction = () => {
    switch(locale) {
      case 'fa':
      case 'ar':
        return 'ltr';
      case 'tr':
      case 'en':
      default:
        return 'rtl';
    }
  };  
  return (
    <html lang={locale} dir={direction()}>
      <body className="bg-background dark:bg-background-dark text-text dark:text-text-dark flex justify-center font-yekan">
        <NextIntlClientProvider>
          <ReduxProvider>
            <main className="w-[85.5%] ">
              <Header />
              {children}
              <Footer />
            </main>
            <FloatingActions />
          </ReduxProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
