// Next built in imports
import type { Metadata } from "next";
// next-intl
import { routing } from "@/i18n/routing";
import { NextIntlClientProvider, hasLocale } from "next-intl";
// Third party components
import FloatingActions from "@/components/common/FAB/fab";
import Footer from "@/components/common/footer/footer";
import Header from "@/components/common/header/header";
// Redux provider
// Css imports
import "../globals.css";
// Toaster
import { ToastContainer } from "react-toastify";
import Providers from "@/provider/provider";

// metadata
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}>) {
  const { locale } = await params;
  if (!hasLocale(routing.locales, locale)) {
    return "not found";
  }

  const direction = () => {
    switch (locale) {
      case "fa":
      case "ar":
        return "ltr";
      case "tr":
      case "en":
      default:
        return "rtl";
    }
  };
  return (
    <html lang={locale} dir={direction()}>
      <body className="bg-background text-text font-yekan">
        <NextIntlClientProvider>
          <Providers>
            <main className="w-full flex-wrap">
              <Header />
              {children}
              <Footer />
              <ToastContainer />
            </main>
            <FloatingActions />
          </Providers>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
