// Next built in imports
import type { Metadata } from "next";
// next-intl
import { routing } from "@/i18n/routing";
import { NextIntlClientProvider, hasLocale } from "next-intl";
// Css imports
import "./globals.css";
// Third party components
import FloatingActions from "@/components/common/fab";
import Providers from "@/provider/provider";
import TokenRefresher from "@/components/common/TokenRefresher";

// metadata
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}>) {
  // Ensure that the incoming `locale` is valid
  const { locale } = await params;
  if (!hasLocale(routing.locales, locale)) {
    return "not found";
  }

  const direction = () => {
    switch (locale) {
      case "fa":
      case "ar":
        return "rtl";
      case "tr":
      case "en":
      default:
        return "ltr";
    }
  };

  return (
    <html lang={locale} dir={direction()}>
      <body className="bg-background  text-text w-[100%] max-h-screen flex justify-center font-yekan">
        <NextIntlClientProvider>
          <Providers>
            <div className="w-full">{children}</div>
            <FloatingActions />
            <TokenRefresher />
          </Providers>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
