// Next built in imports
import type { Metadata } from "next";
// next-intl
import { NextIntlClientProvider, hasLocale } from "next-intl";
import { routing } from "@/i18n/routing";
// Redux provider
import { ReduxProvider } from "@/utils/providers/redux-provider";
// Css imports
import "../globals.css";
// Third party components
import FloatingActions from "@/components/common/FAB/fab";
import Auth from "@/components/auth/auth";

// metadata
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}>) {
  // Ensure that the incoming `locale` is valid
  const { locale } = await params;
  if (!hasLocale(routing.locales, locale)) {
    return "not found";
  }

  const direction = () => {
    switch(locale) {
      case 'fa':
      case 'ar':
        return 'ltr';
      case 'tr':
      case 'en':
      default:
        return 'rtl';
    }
  };  

  return (
    <html lang={locale} dir={direction()}>
      <body className="bg-background  text-text  flex justify-center font-yekan">
        <NextIntlClientProvider>
          <ReduxProvider>
            <main className="w-[100%] max-h-screen ">
              <div className="flex justify-between max-h-screen p-[16px]">
                <Auth />
                <div className="w-[55%] max-[1300px]:w-full flex justify-center">
                  <div className="max-[1300px]:w-[80%] mt-10 max-[600px]:w-[100%]  max-[1300px]:justify-center my-auto w-[390px] max-h-[calc(100vh-16px)] flex flex-wrap flex-col gap-[24px]">
                    {children}
                  </div>
                </div>
              </div>
            </main>
            <FloatingActions />
          </ReduxProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
