// import Auth from '@/components/auth/auth'
// import React from 'react'
// import "../(main)/globals.css"


// export default function AuthLayout({ children }: { children: React.ReactNode }) {
//     return (
//         <html>
//             <body className=''>
//                 <div className='px-[40px] flex justify-between'><Auth />{children}</div>
//             </body>
//         </html>
//     )
// }






// Next built in imports
import type { Metadata } from "next";
// next-intl
import { NextIntlClientProvider, hasLocale } from "next-intl";
import { routing } from "@/i18n/routing";
// Css imports
import { ReduxProvider } from "@/utils/providers/redux-provider";
import "../(main)/globals.css";
import FloatingActions from "@/components/common/FAB/fab";
import Auth from "@/components/auth/auth";

// metadata
export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout({
    children,
    params,
}: Readonly<{
    children: React.ReactNode;
    params: Promise<{ locale: string }>;
}>) {
    // Ensure that the incoming `locale` is valid
    const { locale } = await params;
    if (!hasLocale(routing.locales, locale)) {
        return "not found";
    }
    return (
        <html lang={locale}>
            <body className="bg-background dark:bg-background-dark text-text dark:text-text-dark flex justify-center font-yekan">
                <NextIntlClientProvider>
                    <ReduxProvider>
                        <main className="w-[100%] max-h-[97vh] p-[16px]">
                            <div className='  my-[auto] flex justify-between'>
                                <Auth />
                                <div className="w-[55%] max-[1300px]:w-full flex justify-center">{children}</div>
                            </div>
                        </main>
                        <FloatingActions />
                    </ReduxProvider>
                </NextIntlClientProvider>
            </body>
        </html>
    );
}


