// Next built in imports
import type { Metadata } from "next";
// Css imports
import "../globals.css";
// Third party components
import Auth from "@/components/common/auth";

// metadata
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function AuthLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="w-[100%] max-h-screen ">
      <div className="flex justify-center max-h-screen p-[16px]">
        <div className="w-[100%] animate-fade-left max-[1300px]:w-full flex justify-center">
          <div className="max-[1300px]:w-[80%] mt-10 max-[600px]:w-[100%]  max-[1300px]:justify-center my-auto w-[390px] max-h-[calc(100vh-16px)] flex flex-wrap flex-col gap-[24px]">
            {children}
          </div>
        </div>
        <Auth />
      </div>
    </div>
  );
}
